name: code-check
on:
  push:
    paths:
      - '**.py'

jobs:
  check-code-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Install ruff
        run: pip3 install ruff mypy

      - name: Check formatting
        run: ruff check . && mypy .
